version: "2.2"
services:
  jobmanager:
    image: flink:1.20.3-scala_2.12-java8
    ports:
      - "8081:8081"
    command: standalone-job --job-classname com.job.ClassName
    volumes:
      - ../artifacts:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2

  taskmanager:
    image: flink:1.20.3-scala_2.12-java8
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - ../artifacts:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2